[pytest]
addopts = -vv --alluredir=./allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S

markers =
    auth: tests for auth api
    movies: tests for movies api
    positive: positive test cases
    negative: negative test cases
    roles: tests for role-based access
    smoke: smoke tests


;[pytest]
;addopts = -v -s --html=report.html --tb=short  # Дополнительные опции запуска
;python_files = test_*.py                      # Шаблон файлов с тестами
;python_classes = Test*                        # Шаблон классов с тестами
;python_functions = test_*                     # Шаблон функций с тестами
;markers =
;    smoke: быстрые проверки
;    regression: регрессионные тесты
;    api: API-тесты
;    ui: UI-тесты